"""
program to guess the number which is generated by the computer randomely from 1-10,
you have only 3 chance to gaussing the number 

"""
import random
print("\n\n\n*********************************************************************************")
print("\n\n\n\t\t\tWelcome to number guessing game made by : amrit panta ")
limit = 3
attempt = 0
guess_number = random.randint(1, 10)
# print(guess_number)
while 1:
    print("\n\n\n*********************************************************************************")
    while limit != 0:
        num = int(input("\n\nEnter the number :-> "))
        try:
            if num == guess_number:
                attempt += 1
                print(
                    f"Congratulation your guess is correct at {attempt} attempt")
                limit -= 1
            elif num > guess_number:
                limit -= 1
                attempt += 1
                if limit == 0:
                    break
                print(
                    f'{num} is greater than guess number , Guess smaller number than {num}')

                print(f'Remaining chance :{limit}')
            elif num < guess_number:
                limit -= 1
                attempt += 1
                if limit == 0:
                    break
                print(
                    f'{num} is less than guess number , Guess greater number than {num}')

                print(f'Remaining chance :{limit}')

        except Exception as e:
            print("Enter only number as input , you have enter other character ...")

    print(f'\n\n\n\t\tActually  number is {guess_number}')
    print("\n\n\n*********************************************************************************")
    a = input("\n\npress 'q' for new  game or Enter any key for exit ->: ").lower()
    if a == 'q':
        limit = 3
        continue
    else:
        break


print("\n\n\n*********************************************************************************")
